### ISSUE TITLE
Calendar behaviour error on elixir 1.8

### ISSUE THREAD

**Issue by shahryarjb** [jalaali/elixir-jalaali#8]
Hello, I have some error that I think it was fixed before elixir 1.6 in blow link 
https://github.com/jalaali/elixir-jalaali/issues/5

but in this version I mean elixir 1.8 these error were shown me again 

## Error 

```
warning: function day_of_era/3 required by behaviour Calendar is not implemented (in module Jalaali.Calendar)
  lib/jalaali/calendar.ex:1

warning: function day_of_year/3 required by behaviour Calendar is not implemented (in module Jalaali.Calendar)
  lib/jalaali/calendar.ex:1

warning: function months_in_year/1 required by behaviour Calendar is not implemented (in module Jalaali.Calendar)
  lib/jalaali/calendar.ex:1

warning: function quarter_of_year/3 required by behaviour Calendar is not implemented (in module Jalaali.Calendar)
  lib/jalaali/calendar.ex:1

warning: function year_of_era/1 required by behaviour Calendar is not implemented (in module Jalaali.Calendar)
  lib/jalaali/calendar.ex:1
```

Thanks

**Comment by alisinabh** [comment]
Hi @shahryarjb,

These warnings were because of the new functionalities of the Calendar module introduced in elixir `1.8`, And the functionalities of the Jalaali calendar was intact. However the new features in elixir `1.8` would't work with `jalaali < 0.3.0`.

I have implemented the new calendar features in Jalaali package version `0.3.0`. Please upgrade your jalaali version in your `mix.exs` file.

Thank you.
